stages:
  - test

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

test:
  stage: test
  image: pytorch/pytorch:latest
  before_script:
    - python -m venv venv
    - source venv/bin/activate
    - pip install --upgrade pip
    - pip install -r backend/requirements.txt --upgrade --force-reinstall
    - pip install coverage
  script:
    - coverage run -m unittest discover backend/tests
    - coverage report -m
    - coverage xml
  coverage: '/^TOTAL.*\s+(\d+\%)$/'
  artifacts:
    paths:
      - coverage.xml
    expire_in: 1 week
