stages:
  - test

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  PYTHONPATH: "$CI_PROJECT_DIR/backend"
  FAST_MODE: 1

cache:
  paths:
    - .cache/pip
    - venv/

test:
  stage: test
  image: pytorch/pytorch:latest
  # image: pytorch/pytorch:2.3.0-cuda12.1-cudnn8-runtime
  before_script:
    - python -m venv venv
    - source venv/bin/activate
    - pip install -r backend/requirements.txt
    - pip install coverage
    - pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu # This is fast as compare to GPU
    #- pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

  script:
    - export PYTHONPATH=$CI_PROJECT_DIR/backend
    - python -c "from PIL import Image; Image.open('backend/uploads/image.png').verify(); print('Image is valid')"
    - ls -lh backend/uploads/image.png
    - ls -l backend/uploads
    - coverage run -m unittest discover backend/tests
    - coverage report -m
    - coverage xml
  coverage: '/^TOTAL.*\s+(\d+\%)$/'
  artifacts:
    paths:
      - coverage.xml
    expire_in: 1 week
