# .gitlab-ci.yml for Python backend with pytest
stages:
  - test

test_backend:
  stage: test
  image: python:3.12
  before_script:
    - python --version
    - pip install --upgrade pip
    - pip install -r backend/requirements.txt
  script:
    - pytest backend/models/tests/ backend/app/tests/ || pytest backend/tests/
  artifacts:
    when: always
    paths:
      - .pytest_cache/
    reports:
      junit: junit.xml
  only:
    - merge_requests
    - main
    - master
