# .gitlab-ci.yml for Python backend with pytest
stages:
  - test

test_backend:
  stage: test
  image: python:3.10
  before_script:
  - python -m venv venv
  - source venv/bin/activate
  - python -m pip install --upgrade pip
  - python -m pip install -r backend/requirements.txt
  script:
  - source venv/bin/activate
  - python -m pytest backend/tests/ --junitxml=junit.xml
  artifacts:
    when: always
    paths:
      - .pytest_cache/
    reports:
      junit: junit.xml
  only:
    - merge_requests
    - main
    - master
