# .gitlab-ci.yml for Python backend with pytest
stages:
  - build
  - test

test_backend:
  stage: test
  image: pytorch/pytorch:latest
  before_script:
    - python --version
    - pip install --upgrade pip
    - pip install -r backend/requirements.txt
    - export PYTHONPATH=$PYTHONPATH:$(pwd)/backend
    - apt-get update && apt-get install -y libgl1 libglib2.0-0
  script:
    - pytest backend/tests/ --junitxml=junit.xml
  artifacts:
    when: always
    paths:
      - .pytest_cache/
    reports:
      junit: junit.xml
  only:
    - merge_requests
    - main
    - master
